### ISSUE TITLE
你更改个人信息的接口是不是挂了

### ISSUE THREAD

**Issue by isBoom** [sirodeneko/singo#1]

**Comment by sirodeneko** [comment]
的确有点奇怪，时好时坏

**Comment by sirodeneko** [comment]
我大概明白了，上传的表单中没有头像信息，后端报错
`avatar: ""
birthday: 975945600
birthdays: 975945600000
nickname: "千叶酱"
sex: "保密"
sign: "发出咕咕咕的声音 嘿嘿↵٩(๑❛ᴗ❛๑)۶"`
假设修改了头像，就有了头像信息，就可以正常修改了
`avatar: "upload/avatar/271009e5-e3dc-46db-8d78-1f35a80256c0.jpg"
birthday: 975945600
birthdays: 975945600000
nickname: "千叶小老板"
sex: "保密"
sign: "发出咕咕咕的声音 嘿嘿↵٩(๑❛ᴗ❛๑)۶"`

**Comment by isBoom** [comment]
👍

**Comment by isBoom** [comment]
但是一般来说不一定修改头像吧

**Comment by sirodeneko** [comment]
没错是我当时留下的锅😂

**Comment by sirodeneko** [comment]
已经修复了
